version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: next-js-test
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./component:/app/component
      - ./logo.png
      
  
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
